//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import javax.xml.ws.WebFault;

@WebFault(name = "BusinessException", targetNamespace = "http://webservices.gdo.equitalia.it/")
public class BusinessException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessException_Exception(String message, BusinessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public BusinessException_Exception(String message, BusinessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.equitalia.gdo.webservices.client.BusinessException
     */
    public BusinessException getFaultInfo() {
        return faultInfo;
    }

}
