//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filtroEnteBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filtroEnteBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://webservices.gdo.equitalia.it/}abstractFiltroBean">
 *       &lt;sequence>
 *         &lt;element name="codiceEnte" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codiceUfficioEnte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoUfficioEnte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filtroEnteBean", namespace = "http://webservices.gdo.equitalia.it/", propOrder = {
    "codiceEnte",
    "codiceUfficioEnte",
    "tipoUfficioEnte"
})
public class FiltroEnteBean
    extends AbstractFiltroBean
{

    protected Integer codiceEnte;
    protected String codiceUfficioEnte;
    protected String tipoUfficioEnte;

    /**
     * Gets the value of the codiceEnte property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodiceEnte() {
        return codiceEnte;
    }

    /**
     * Sets the value of the codiceEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodiceEnte(Integer value) {
        this.codiceEnte = value;
    }

    /**
     * Gets the value of the codiceUfficioEnte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceUfficioEnte() {
        return codiceUfficioEnte;
    }

    /**
     * Sets the value of the codiceUfficioEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceUfficioEnte(String value) {
        this.codiceUfficioEnte = value;
    }

    /**
     * Gets the value of the tipoUfficioEnte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoUfficioEnte() {
        return tipoUfficioEnte;
    }

    /**
     * Sets the value of the tipoUfficioEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoUfficioEnte(String value) {
        this.tipoUfficioEnte = value;
    }

}
