//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for newsBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newsBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://webservices.gdo.equitalia.it/}beanVersionabile">
 *       &lt;sequence>
 *         &lt;element name="agente" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="allegato" type="{http://webservices.gdo.equitalia.it/}allegatoBean" minOccurs="0"/>
 *         &lt;element name="dataFinePubblicazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataInizioPubblicazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descrizioneStato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descrizioneTipoUtente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ente" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="filtroAmbito" type="{http://webservices.gdo.equitalia.it/}filtroAmbitoBean" minOccurs="0"/>
 *         &lt;element name="filtroEnte" type="{http://webservices.gdo.equitalia.it/}filtroEnteBean" minOccurs="0"/>
 *         &lt;element name="filtroProvinciaEnte" type="{http://webservices.gdo.equitalia.it/}filtroProvinciaEnteBean" minOccurs="0"/>
 *         &lt;element name="filtroRegioneAgente" type="{http://webservices.gdo.equitalia.it/}filtroRegioneAgenteBean" minOccurs="0"/>
 *         &lt;element name="filtroRegioneEnte" type="{http://webservices.gdo.equitalia.it/}filtroRegioneEnteBean" minOccurs="0"/>
 *         &lt;element name="filtroServizioAgente" type="{http://webservices.gdo.equitalia.it/}filtroServizioAgenteBean" minOccurs="0"/>
 *         &lt;element name="filtroServizioEnte" type="{http://webservices.gdo.equitalia.it/}filtroServizioEnteBean" minOccurs="0"/>
 *         &lt;element name="filtroSocieta" type="{http://webservices.gdo.equitalia.it/}filtroSocietaBean" minOccurs="0"/>
 *         &lt;element name="filtroTipologiaEnte" type="{http://webservices.gdo.equitalia.it/}filtroTipologiaEnteBean" minOccurs="0"/>
 *         &lt;element name="stato" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="svecchiata" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="testo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="titolo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="visualizzaPopUp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newsBean", namespace = "http://webservices.gdo.equitalia.it/", propOrder = {
    "agente",
    "allegato",
    "dataFinePubblicazione",
    "dataInizioPubblicazione",
    "descrizioneStato",
    "descrizioneTipoUtente",
    "ente",
    "filtroAmbito",
    "filtroEnte",
    "filtroProvinciaEnte",
    "filtroRegioneAgente",
    "filtroRegioneEnte",
    "filtroServizioAgente",
    "filtroServizioEnte",
    "filtroSocieta",
    "filtroTipologiaEnte",
    "stato",
    "svecchiata",
    "testo",
    "titolo",
    "visualizzaPopUp"
})
public class NewsBean
    extends BeanVersionabile
{

    protected Boolean agente;
    protected AllegatoBean allegato;
    protected String dataFinePubblicazione;
    protected String dataInizioPubblicazione;
    protected String descrizioneStato;
    protected String descrizioneTipoUtente;
    protected Boolean ente;
    protected FiltroAmbitoBean filtroAmbito;
    protected FiltroEnteBean filtroEnte;
    protected FiltroProvinciaEnteBean filtroProvinciaEnte;
    protected FiltroRegioneAgenteBean filtroRegioneAgente;
    protected FiltroRegioneEnteBean filtroRegioneEnte;
    protected FiltroServizioAgenteBean filtroServizioAgente;
    protected FiltroServizioEnteBean filtroServizioEnte;
    protected FiltroSocietaBean filtroSocieta;
    protected FiltroTipologiaEnteBean filtroTipologiaEnte;
    protected Integer stato;
    protected Boolean svecchiata;
    protected String testo;
    protected String titolo;
    protected boolean visualizzaPopUp;

    /**
     * Gets the value of the agente property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAgente() {
        return agente;
    }

    /**
     * Sets the value of the agente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAgente(Boolean value) {
        this.agente = value;
    }

    /**
     * Gets the value of the allegato property.
     * 
     * @return
     *     possible object is
     *     {@link AllegatoBean }
     *     
     */
    public AllegatoBean getAllegato() {
        return allegato;
    }

    /**
     * Sets the value of the allegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllegatoBean }
     *     
     */
    public void setAllegato(AllegatoBean value) {
        this.allegato = value;
    }

    /**
     * Gets the value of the dataFinePubblicazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFinePubblicazione() {
        return dataFinePubblicazione;
    }

    /**
     * Sets the value of the dataFinePubblicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFinePubblicazione(String value) {
        this.dataFinePubblicazione = value;
    }

    /**
     * Gets the value of the dataInizioPubblicazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataInizioPubblicazione() {
        return dataInizioPubblicazione;
    }

    /**
     * Sets the value of the dataInizioPubblicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInizioPubblicazione(String value) {
        this.dataInizioPubblicazione = value;
    }

    /**
     * Gets the value of the descrizioneStato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizioneStato() {
        return descrizioneStato;
    }

    /**
     * Sets the value of the descrizioneStato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizioneStato(String value) {
        this.descrizioneStato = value;
    }

    /**
     * Gets the value of the descrizioneTipoUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizioneTipoUtente() {
        return descrizioneTipoUtente;
    }

    /**
     * Sets the value of the descrizioneTipoUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizioneTipoUtente(String value) {
        this.descrizioneTipoUtente = value;
    }

    /**
     * Gets the value of the ente property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnte() {
        return ente;
    }

    /**
     * Sets the value of the ente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnte(Boolean value) {
        this.ente = value;
    }

    /**
     * Gets the value of the filtroAmbito property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroAmbitoBean }
     *     
     */
    public FiltroAmbitoBean getFiltroAmbito() {
        return filtroAmbito;
    }

    /**
     * Sets the value of the filtroAmbito property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroAmbitoBean }
     *     
     */
    public void setFiltroAmbito(FiltroAmbitoBean value) {
        this.filtroAmbito = value;
    }

    /**
     * Gets the value of the filtroEnte property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroEnteBean }
     *     
     */
    public FiltroEnteBean getFiltroEnte() {
        return filtroEnte;
    }

    /**
     * Sets the value of the filtroEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroEnteBean }
     *     
     */
    public void setFiltroEnte(FiltroEnteBean value) {
        this.filtroEnte = value;
    }

    /**
     * Gets the value of the filtroProvinciaEnte property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroProvinciaEnteBean }
     *     
     */
    public FiltroProvinciaEnteBean getFiltroProvinciaEnte() {
        return filtroProvinciaEnte;
    }

    /**
     * Sets the value of the filtroProvinciaEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroProvinciaEnteBean }
     *     
     */
    public void setFiltroProvinciaEnte(FiltroProvinciaEnteBean value) {
        this.filtroProvinciaEnte = value;
    }

    /**
     * Gets the value of the filtroRegioneAgente property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroRegioneAgenteBean }
     *     
     */
    public FiltroRegioneAgenteBean getFiltroRegioneAgente() {
        return filtroRegioneAgente;
    }

    /**
     * Sets the value of the filtroRegioneAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroRegioneAgenteBean }
     *     
     */
    public void setFiltroRegioneAgente(FiltroRegioneAgenteBean value) {
        this.filtroRegioneAgente = value;
    }

    /**
     * Gets the value of the filtroRegioneEnte property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroRegioneEnteBean }
     *     
     */
    public FiltroRegioneEnteBean getFiltroRegioneEnte() {
        return filtroRegioneEnte;
    }

    /**
     * Sets the value of the filtroRegioneEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroRegioneEnteBean }
     *     
     */
    public void setFiltroRegioneEnte(FiltroRegioneEnteBean value) {
        this.filtroRegioneEnte = value;
    }

    /**
     * Gets the value of the filtroServizioAgente property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroServizioAgenteBean }
     *     
     */
    public FiltroServizioAgenteBean getFiltroServizioAgente() {
        return filtroServizioAgente;
    }

    /**
     * Sets the value of the filtroServizioAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroServizioAgenteBean }
     *     
     */
    public void setFiltroServizioAgente(FiltroServizioAgenteBean value) {
        this.filtroServizioAgente = value;
    }

    /**
     * Gets the value of the filtroServizioEnte property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroServizioEnteBean }
     *     
     */
    public FiltroServizioEnteBean getFiltroServizioEnte() {
        return filtroServizioEnte;
    }

    /**
     * Sets the value of the filtroServizioEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroServizioEnteBean }
     *     
     */
    public void setFiltroServizioEnte(FiltroServizioEnteBean value) {
        this.filtroServizioEnte = value;
    }

    /**
     * Gets the value of the filtroSocieta property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroSocietaBean }
     *     
     */
    public FiltroSocietaBean getFiltroSocieta() {
        return filtroSocieta;
    }

    /**
     * Sets the value of the filtroSocieta property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroSocietaBean }
     *     
     */
    public void setFiltroSocieta(FiltroSocietaBean value) {
        this.filtroSocieta = value;
    }

    /**
     * Gets the value of the filtroTipologiaEnte property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroTipologiaEnteBean }
     *     
     */
    public FiltroTipologiaEnteBean getFiltroTipologiaEnte() {
        return filtroTipologiaEnte;
    }

    /**
     * Sets the value of the filtroTipologiaEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroTipologiaEnteBean }
     *     
     */
    public void setFiltroTipologiaEnte(FiltroTipologiaEnteBean value) {
        this.filtroTipologiaEnte = value;
    }

    /**
     * Gets the value of the stato property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStato() {
        return stato;
    }

    /**
     * Sets the value of the stato property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStato(Integer value) {
        this.stato = value;
    }

    /**
     * Gets the value of the svecchiata property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSvecchiata() {
        return svecchiata;
    }

    /**
     * Sets the value of the svecchiata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSvecchiata(Boolean value) {
        this.svecchiata = value;
    }

    /**
     * Gets the value of the testo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesto() {
        return testo;
    }

    /**
     * Sets the value of the testo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesto(String value) {
        this.testo = value;
    }

    /**
     * Gets the value of the titolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo() {
        return titolo;
    }

    /**
     * Sets the value of the titolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo(String value) {
        this.titolo = value;
    }

    /**
     * Gets the value of the visualizzaPopUp property.
     * 
     */
    public boolean isVisualizzaPopUp() {
        return visualizzaPopUp;
    }

    /**
     * Sets the value of the visualizzaPopUp property.
     * 
     */
    public void setVisualizzaPopUp(boolean value) {
        this.visualizzaPopUp = value;
    }

}
