//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package it.equitalia.gdo.webservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "NewsFrontendWebServiceDelegate", targetNamespace = "http://webservices.gdo.equitalia.it/")
public interface NewsFrontendWebServiceDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.equitalia.gdo.webservices.client.ListaNews
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteEnte", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteEnte")
    @ResponseWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteEnteResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteEnteResponse")
    public ListaNews recuperaNewsAttiveDestinateAdUtenteEnte(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.equitalia.gdo.webservices.client.ListaNews
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteAgente", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteAgente")
    @ResponseWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteAgenteResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteAgenteResponse")
    public ListaNews recuperaNewsAttiveDestinateAdUtenteAgente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.equitalia.gdo.webservices.client.ListaNews
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaNewsAttivePerAltriUtenti", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttivePerAltriUtenti")
    @ResponseWrapper(localName = "recuperaNewsAttivePerAltriUtentiResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttivePerAltriUtentiResponse")
    public ListaNews recuperaNewsAttivePerAltriUtenti(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BusinessException_Exception
    ;
    
    /**
     * 
     * @param arg0
     * @return
     *     returns it.equitalia.gdo.webservices.client.ListaNews
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaNewsAttivePerUtenteEsterno", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttivePerUtenteEsterno")
    @ResponseWrapper(localName = "recuperaNewsAttivePerUtenteEsternoResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttivePerUtenteEsternoResponse")
    public ListaNews recuperaNewsAttivePerUtenteEsterno(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BusinessException_Exception
    ;

}
