//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "NewsFrontendWebServiceService", targetNamespace = "http://webservices.gdo.equitalia.it/", wsdlLocation = "META-INF/wsdl/NewsFrontendWebServiceService.wsdl")
public class NewsFrontendWebServiceService
    extends Service
{

    private final static URL NEWSFRONTENDWEBSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = it.equitalia.gdo.webservices.client.NewsFrontendWebServiceService.class.getResource("/META-INF/wsdl/NewsFrontendWebServiceService.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/NewsFrontendWebServiceService.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        NEWSFRONTENDWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public NewsFrontendWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewsFrontendWebServiceService() {
        super(NEWSFRONTENDWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservices.gdo.equitalia.it/", "NewsFrontendWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns NewsFrontendWebServiceDelegate
     */
    @WebEndpoint(name = "NewsFrontendWebServicePort")
    public NewsFrontendWebServiceDelegate getNewsFrontendWebServicePort() {
        return (NewsFrontendWebServiceDelegate)super.getPort(new QName("http://webservices.gdo.equitalia.it/", "NewsFrontendWebServicePort"), NewsFrontendWebServiceDelegate.class);
    }

}
