//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "NewsFrontendWebServiceDelegate", targetNamespace = "http://webservices.gdo.equitalia.it/")
public interface NewsFrontendWebServiceDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.equitalia.gdo.webservices.client.ListaNews
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteEnte", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteEnte")
    @ResponseWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteEnteResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteEnteResponse")
    public ListaNews recuperaNewsAttiveDestinateAdUtenteEnte(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.equitalia.gdo.webservices.client.ListaNews
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteAgente", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteAgente")
    @ResponseWrapper(localName = "recuperaNewsAttiveDestinateAdUtenteAgenteResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.client.RecuperaNewsAttiveDestinateAdUtenteAgenteResponse")
    public ListaNews recuperaNewsAttiveDestinateAdUtenteAgente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BusinessException_Exception
    ;

}
