//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package it.equitalia.gdo.webservices.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.equitalia.gdo.webservices.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RecuperaNewsAttiveDestinateAdUtenteEnte_QNAME = new QName("http://webservices.gdo.equitalia.it/", "recuperaNewsAttiveDestinateAdUtenteEnte");
    private final static QName _RecuperaNewsAttivePerAltriUtentiResponse_QNAME = new QName("http://webservices.gdo.equitalia.it/", "recuperaNewsAttivePerAltriUtentiResponse");
    private final static QName _RecuperaNewsAttiveDestinateAdUtenteAgente_QNAME = new QName("http://webservices.gdo.equitalia.it/", "recuperaNewsAttiveDestinateAdUtenteAgente");
    private final static QName _RecuperaNewsAttiveDestinateAdUtenteEnteResponse_QNAME = new QName("http://webservices.gdo.equitalia.it/", "recuperaNewsAttiveDestinateAdUtenteEnteResponse");
    private final static QName _BusinessException_QNAME = new QName("http://webservices.gdo.equitalia.it/", "BusinessException");
    private final static QName _RecuperaNewsAttiveDestinateAdUtenteAgenteResponse_QNAME = new QName("http://webservices.gdo.equitalia.it/", "recuperaNewsAttiveDestinateAdUtenteAgenteResponse");
    private final static QName _RecuperaNewsAttivePerAltriUtenti_QNAME = new QName("http://webservices.gdo.equitalia.it/", "recuperaNewsAttivePerAltriUtenti");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.equitalia.gdo.webservices.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusinessException }
     * 
     */
    public BusinessException createBusinessException() {
        return new BusinessException();
    }

    /**
     * Create an instance of {@link RecuperaNewsAttiveDestinateAdUtenteEnte }
     * 
     */
    public RecuperaNewsAttiveDestinateAdUtenteEnte createRecuperaNewsAttiveDestinateAdUtenteEnte() {
        return new RecuperaNewsAttiveDestinateAdUtenteEnte();
    }

    /**
     * Create an instance of {@link RecuperaNewsAttiveDestinateAdUtenteAgente }
     * 
     */
    public RecuperaNewsAttiveDestinateAdUtenteAgente createRecuperaNewsAttiveDestinateAdUtenteAgente() {
        return new RecuperaNewsAttiveDestinateAdUtenteAgente();
    }

    /**
     * Create an instance of {@link RecuperaNewsAttivePerAltriUtenti }
     * 
     */
    public RecuperaNewsAttivePerAltriUtenti createRecuperaNewsAttivePerAltriUtenti() {
        return new RecuperaNewsAttivePerAltriUtenti();
    }

    /**
     * Create an instance of {@link RecuperaNewsAttivePerAltriUtentiResponse }
     * 
     */
    public RecuperaNewsAttivePerAltriUtentiResponse createRecuperaNewsAttivePerAltriUtentiResponse() {
        return new RecuperaNewsAttivePerAltriUtentiResponse();
    }

    /**
     * Create an instance of {@link RecuperaNewsAttiveDestinateAdUtenteAgenteResponse }
     * 
     */
    public RecuperaNewsAttiveDestinateAdUtenteAgenteResponse createRecuperaNewsAttiveDestinateAdUtenteAgenteResponse() {
        return new RecuperaNewsAttiveDestinateAdUtenteAgenteResponse();
    }

    /**
     * Create an instance of {@link RecuperaNewsAttiveDestinateAdUtenteEnteResponse }
     * 
     */
    public RecuperaNewsAttiveDestinateAdUtenteEnteResponse createRecuperaNewsAttiveDestinateAdUtenteEnteResponse() {
        return new RecuperaNewsAttiveDestinateAdUtenteEnteResponse();
    }

    /**
     * Create an instance of {@link ListaNews }
     * 
     */
    public ListaNews createListaNews() {
        return new ListaNews();
    }

    /**
     * Create an instance of {@link FiltroTipologiaEnteBean }
     * 
     */
    public FiltroTipologiaEnteBean createFiltroTipologiaEnteBean() {
        return new FiltroTipologiaEnteBean();
    }

    /**
     * Create an instance of {@link FiltroProvinciaEnteBean }
     * 
     */
    public FiltroProvinciaEnteBean createFiltroProvinciaEnteBean() {
        return new FiltroProvinciaEnteBean();
    }

    /**
     * Create an instance of {@link FiltroServizioAgenteBean }
     * 
     */
    public FiltroServizioAgenteBean createFiltroServizioAgenteBean() {
        return new FiltroServizioAgenteBean();
    }

    /**
     * Create an instance of {@link FiltroServizioEnteBean }
     * 
     */
    public FiltroServizioEnteBean createFiltroServizioEnteBean() {
        return new FiltroServizioEnteBean();
    }

    /**
     * Create an instance of {@link FiltroProvinciaBean }
     * 
     */
    public FiltroProvinciaBean createFiltroProvinciaBean() {
        return new FiltroProvinciaBean();
    }

    /**
     * Create an instance of {@link FiltroSocietaBean }
     * 
     */
    public FiltroSocietaBean createFiltroSocietaBean() {
        return new FiltroSocietaBean();
    }

    /**
     * Create an instance of {@link FiltroServizioAltriUtentiBean }
     * 
     */
    public FiltroServizioAltriUtentiBean createFiltroServizioAltriUtentiBean() {
        return new FiltroServizioAltriUtentiBean();
    }

    /**
     * Create an instance of {@link FiltroAmbitoBean }
     * 
     */
    public FiltroAmbitoBean createFiltroAmbitoBean() {
        return new FiltroAmbitoBean();
    }

    /**
     * Create an instance of {@link AllegatoBean }
     * 
     */
    public AllegatoBean createAllegatoBean() {
        return new AllegatoBean();
    }

    /**
     * Create an instance of {@link BeanVersionabile }
     * 
     */
    public BeanVersionabile createBeanVersionabile() {
        return new BeanVersionabile();
    }

    /**
     * Create an instance of {@link FiltroRegioneEnteBean }
     * 
     */
    public FiltroRegioneEnteBean createFiltroRegioneEnteBean() {
        return new FiltroRegioneEnteBean();
    }

    /**
     * Create an instance of {@link NewsBean }
     * 
     */
    public NewsBean createNewsBean() {
        return new NewsBean();
    }

    /**
     * Create an instance of {@link FiltroEnteBean }
     * 
     */
    public FiltroEnteBean createFiltroEnteBean() {
        return new FiltroEnteBean();
    }

    /**
     * Create an instance of {@link FiltroRegioneAgenteBean }
     * 
     */
    public FiltroRegioneAgenteBean createFiltroRegioneAgenteBean() {
        return new FiltroRegioneAgenteBean();
    }

    /**
     * Create an instance of {@link FiltroRegioneBean }
     * 
     */
    public FiltroRegioneBean createFiltroRegioneBean() {
        return new FiltroRegioneBean();
    }

    /**
     * Create an instance of {@link FiltroServizioBean }
     * 
     */
    public FiltroServizioBean createFiltroServizioBean() {
        return new FiltroServizioBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecuperaNewsAttiveDestinateAdUtenteEnte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "recuperaNewsAttiveDestinateAdUtenteEnte")
    public JAXBElement<RecuperaNewsAttiveDestinateAdUtenteEnte> createRecuperaNewsAttiveDestinateAdUtenteEnte(RecuperaNewsAttiveDestinateAdUtenteEnte value) {
        return new JAXBElement<RecuperaNewsAttiveDestinateAdUtenteEnte>(_RecuperaNewsAttiveDestinateAdUtenteEnte_QNAME, RecuperaNewsAttiveDestinateAdUtenteEnte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecuperaNewsAttivePerAltriUtentiResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "recuperaNewsAttivePerAltriUtentiResponse")
    public JAXBElement<RecuperaNewsAttivePerAltriUtentiResponse> createRecuperaNewsAttivePerAltriUtentiResponse(RecuperaNewsAttivePerAltriUtentiResponse value) {
        return new JAXBElement<RecuperaNewsAttivePerAltriUtentiResponse>(_RecuperaNewsAttivePerAltriUtentiResponse_QNAME, RecuperaNewsAttivePerAltriUtentiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecuperaNewsAttiveDestinateAdUtenteAgente }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "recuperaNewsAttiveDestinateAdUtenteAgente")
    public JAXBElement<RecuperaNewsAttiveDestinateAdUtenteAgente> createRecuperaNewsAttiveDestinateAdUtenteAgente(RecuperaNewsAttiveDestinateAdUtenteAgente value) {
        return new JAXBElement<RecuperaNewsAttiveDestinateAdUtenteAgente>(_RecuperaNewsAttiveDestinateAdUtenteAgente_QNAME, RecuperaNewsAttiveDestinateAdUtenteAgente.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecuperaNewsAttiveDestinateAdUtenteEnteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "recuperaNewsAttiveDestinateAdUtenteEnteResponse")
    public JAXBElement<RecuperaNewsAttiveDestinateAdUtenteEnteResponse> createRecuperaNewsAttiveDestinateAdUtenteEnteResponse(RecuperaNewsAttiveDestinateAdUtenteEnteResponse value) {
        return new JAXBElement<RecuperaNewsAttiveDestinateAdUtenteEnteResponse>(_RecuperaNewsAttiveDestinateAdUtenteEnteResponse_QNAME, RecuperaNewsAttiveDestinateAdUtenteEnteResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "BusinessException")
    public JAXBElement<BusinessException> createBusinessException(BusinessException value) {
        return new JAXBElement<BusinessException>(_BusinessException_QNAME, BusinessException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecuperaNewsAttiveDestinateAdUtenteAgenteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "recuperaNewsAttiveDestinateAdUtenteAgenteResponse")
    public JAXBElement<RecuperaNewsAttiveDestinateAdUtenteAgenteResponse> createRecuperaNewsAttiveDestinateAdUtenteAgenteResponse(RecuperaNewsAttiveDestinateAdUtenteAgenteResponse value) {
        return new JAXBElement<RecuperaNewsAttiveDestinateAdUtenteAgenteResponse>(_RecuperaNewsAttiveDestinateAdUtenteAgenteResponse_QNAME, RecuperaNewsAttiveDestinateAdUtenteAgenteResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecuperaNewsAttivePerAltriUtenti }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.gdo.equitalia.it/", name = "recuperaNewsAttivePerAltriUtenti")
    public JAXBElement<RecuperaNewsAttivePerAltriUtenti> createRecuperaNewsAttivePerAltriUtenti(RecuperaNewsAttivePerAltriUtenti value) {
        return new JAXBElement<RecuperaNewsAttivePerAltriUtenti>(_RecuperaNewsAttivePerAltriUtenti_QNAME, RecuperaNewsAttivePerAltriUtenti.class, null, value);
    }

}
