//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.gdo.equitalia.it/")
package it.equitalia.gdo.webservices.client;
