//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "GeuGetUserProfileDelegate", targetNamespace = "http://service.gestionaleutenze.equitaliaservizi.it/")
public interface GeuGetUserProfileDelegate {


    /**
     * 
     * @param getUserProfileRequest
     * @return
     *     returns it.equitalia.gdo.webservices.client.UserProfile
     */
    @WebMethod
    @WebResult(name = "getUserProfileResponse", targetNamespace = "")
    @RequestWrapper(localName = "getUserProfile", targetNamespace = "http://service.gestionaleutenze.equitaliaservizi.it/", className = "it.equitalia.gdo.webservices.client.GetUserProfile")
    @ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://service.gestionaleutenze.equitaliaservizi.it/", className = "it.equitalia.gdo.webservices.client.GetUserProfileResponse")
    public UserProfile getUserProfile(
        @WebParam(name = "getUserProfileRequest", targetNamespace = "")
        UserProfileRequest getUserProfileRequest);

}
