//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.webservices.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="esitoServizio">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="messaggioServizio">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idUtente">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *               &lt;pattern value="[A-Z0-9]*"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="email">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;pattern value="[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*\.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ruolo" type="{http://service.gestionaleutenze.equitaliaservizi.it/}ruolo" minOccurs="0"/>
 *         &lt;element name="servizio" type="{http://service.gestionaleutenze.equitaliaservizi.it/}servizio" minOccurs="0"/>
 *         &lt;element name="listaFunzioni" type="{http://service.gestionaleutenze.equitaliaservizi.it/}funzione" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="listaAmbiti" type="{http://service.gestionaleutenze.equitaliaservizi.it/}ambito" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userProfile", namespace = "http://service.gestionaleutenze.equitaliaservizi.it/", propOrder = {
    "esitoServizio",
    "messaggioServizio",
    "idUtente",
    "email",
    "ruolo",
    "servizio",
    "listaFunzioni",
    "listaAmbiti"
})
public class UserProfile {

    @XmlElement(required = true)
    protected String esitoServizio;
    @XmlElement(required = true)
    protected String messaggioServizio;
    @XmlElement(required = true)
    protected String idUtente;
    @XmlElement(required = true)
    protected String email;
    protected Ruolo ruolo;
    protected Servizio servizio;
    @XmlElement(nillable = true)
    protected List<Funzione> listaFunzioni;
    @XmlElement(nillable = true)
    protected List<Ambito> listaAmbiti;

    /**
     * Gets the value of the esitoServizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsitoServizio() {
        return esitoServizio;
    }

    /**
     * Sets the value of the esitoServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsitoServizio(String value) {
        this.esitoServizio = value;
    }

    /**
     * Gets the value of the messaggioServizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessaggioServizio() {
        return messaggioServizio;
    }

    /**
     * Sets the value of the messaggioServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessaggioServizio(String value) {
        this.messaggioServizio = value;
    }

    /**
     * Gets the value of the idUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdUtente() {
        return idUtente;
    }

    /**
     * Sets the value of the idUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdUtente(String value) {
        this.idUtente = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the ruolo property.
     * 
     * @return
     *     possible object is
     *     {@link Ruolo }
     *     
     */
    public Ruolo getRuolo() {
        return ruolo;
    }

    /**
     * Sets the value of the ruolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ruolo }
     *     
     */
    public void setRuolo(Ruolo value) {
        this.ruolo = value;
    }

    /**
     * Gets the value of the servizio property.
     * 
     * @return
     *     possible object is
     *     {@link Servizio }
     *     
     */
    public Servizio getServizio() {
        return servizio;
    }

    /**
     * Sets the value of the servizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Servizio }
     *     
     */
    public void setServizio(Servizio value) {
        this.servizio = value;
    }

    /**
     * Gets the value of the listaFunzioni property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaFunzioni property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaFunzioni().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Funzione }
     * 
     * 
     */
    public List<Funzione> getListaFunzioni() {
        if (listaFunzioni == null) {
            listaFunzioni = new ArrayList<Funzione>();
        }
        return this.listaFunzioni;
    }

    /**
     * Gets the value of the listaAmbiti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaAmbiti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaAmbiti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ambito }
     * 
     * 
     */
    public List<Ambito> getListaAmbiti() {
        if (listaAmbiti == null) {
            listaAmbiti = new ArrayList<Ambito>();
        }
        return this.listaAmbiti;
    }

}
