//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.svecchiamento.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "SvecchiamentoWebServiceDelegate", targetNamespace = "http://webservices.gdo.equitalia.it/")
public interface SvecchiamentoWebServiceDelegate {


    /**
     * 
     * @return
     *     returns boolean
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invocaSvecchiamento", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.InvocaSvecchiamento")
    @ResponseWrapper(localName = "invocaSvecchiamentoResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.InvocaSvecchiamentoResponse")
    public boolean invocaSvecchiamento()
        throws BusinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invocaSvecchiamentoDocumenti", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.InvocaSvecchiamentoDocumenti")
    @ResponseWrapper(localName = "invocaSvecchiamentoDocumentiResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.InvocaSvecchiamentoDocumentiResponse")
    public boolean invocaSvecchiamentoDocumenti()
        throws BusinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invocaSvecchiamentoNews", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.InvocaSvecchiamentoNews")
    @ResponseWrapper(localName = "invocaSvecchiamentoNewsResponse", targetNamespace = "http://webservices.gdo.equitalia.it/", className = "it.equitalia.gdo.webservices.InvocaSvecchiamentoNewsResponse")
    public boolean invocaSvecchiamentoNews()
        throws BusinessException_Exception
    ;

}
