//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-01/09/2012 05:11 AM(foreman)-fcs)
//


package it.equitalia.gdo.svecchiamento.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "SvecchiamentoWebServiceService", targetNamespace = "http://webservices.gdo.equitalia.it/", wsdlLocation = "META-INF/wsdl/SvecchiamentoWebServiceService.wsdl")
public class SvecchiamentoWebServiceService
    extends Service
{

    private final static URL SVECCHIAMENTOWEBSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = it.equitalia.gdo.svecchiamento.client.SvecchiamentoWebServiceService.class.getResource("/META-INF/wsdl/SvecchiamentoWebServiceService.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/SvecchiamentoWebServiceService.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SVECCHIAMENTOWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public SvecchiamentoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvecchiamentoWebServiceService() {
        super(SVECCHIAMENTOWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservices.gdo.equitalia.it/", "SvecchiamentoWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns SvecchiamentoWebServiceDelegate
     */
    @WebEndpoint(name = "SvecchiamentoWebServicePort")
    public SvecchiamentoWebServiceDelegate getSvecchiamentoWebServicePort() {
        return (SvecchiamentoWebServiceDelegate)super.getPort(new QName("http://webservices.gdo.equitalia.it/", "SvecchiamentoWebServicePort"), SvecchiamentoWebServiceDelegate.class);
    }

}
